/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#23005c",
        "surface-bright": "#3b392c",
        "surface-container-highest": "#373528",
        "on-secondary-fixed-variant": "#00522c",
        "on-surface-variant": "#ccc7ac",
        "surface-variant": "#373528",
        "secondary-fixed": "#6bfda7",
        "on-secondary-container": "#004122",
        "on-tertiary-container": "#7342dd",
        "on-primary-container": "#6d6600",
        "primary": "#ffffff",
        "tertiary-container": "#e9ddff",
        "on-tertiary-fixed-variant": "#5516be",
        "secondary": "#4ae08d",
        "tertiary-fixed": "#e9ddff",
        "outline-variant": "#4a4732",
        "surface-tint": "#d8ca00",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#d8ca00",
        "error-container": "#93000a",
        "on-background": "#e7e3d0",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-secondary-fixed": "#00210f",
        "surface-container": "#212014",
        "surface-container-high": "#2c2a1e",
        "background": "#151409",
        "primary-container": "#FFE44D",
        "on-tertiary": "#3c0091",
        "primary-fixed": "#f5e626",
        "on-primary": "#353100",
        "inverse-surface": "#e7e3d0",
        "inverse-on-surface": "#323124",
        "on-secondary": "#00391d",
        "surface": "#151409",
        "surface-container-lowest": "#100e05",
        "secondary-fixed-dim": "#4ae08d",
        "tertiary": "#ffffff",
        "secondary-container": "#00b86a",
        "on-primary-fixed": "#1f1c00",
        "surface-container-low": "#1d1c10",
        "outline": "#959178",
        "on-surface": "#e7e3d0",
        "on-primary-fixed-variant": "#4d4800",
        "surface-dim": "#151409",
        "tertiary-fixed-dim": "#d0bcff",
        "inverse-primary": "#676000",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "12px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "24px",
        "stack-md": "24px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "body-lg": ["Space Grotesk"],
        "label-sm": ["IBM Plex Mono"],
        "body-md": ["Space Grotesk"],
        "headline-lg": ["Anton"],
        "display-xl": ["Anton"],
        "label-md": ["IBM Plex Mono"],
        "display-xl-mobile": ["Anton"],
        "display-2xl": ["Anton"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "36px", fontWeight: "400", letterSpacing: "0.02em" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "28px", fontWeight: "400", letterSpacing: "0.02em" }],
        "headline-lg": ["40px", { lineHeight: "44px", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "80px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-xl-mobile": ["48px", { lineHeight: "48px", letterSpacing: "0em", fontWeight: "400" }],
        "display-2xl": ["120px", { lineHeight: "110px", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}